server:
  port: 8082

spring: 
  application: 
    name: account-service
  datasource:
    url: jdbc:h2:mem:account_service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}

account:
  api:
    services:
      customer:
        base-url: http://localhost:8081
        relative-path: /api/customer?customerId=
      transaction:
        base-url: http://localhost:8083
        relative-path: /api/transaction

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs