server:
  port: 8082

spring: 
  application: 
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_service
    username: root
    password: 123Oracle$
  jpa: 
    hibernate: 
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs