server:
  port: 8082

spring: 
  application: 
    name: account-service
  datasource:
    url: jdbc:h2:mem:account_service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console:
    enabled: true
  # datasource:
  #   url: jdbc:mysql://localhost:3306/account_service
  #   username: root
  #   password: mydb@123
  # jpa: 
  #   hibernate: 
  #     ddl-auto: none

account:
  api:
    services:
      customer:
        base-url: http://localhost:8081
        relative-path: /api/customer?customerId=
      transaction:
        base-url: http://localhost:8083
        relative-path: /api/transaction

#Kafka Properties
# spring:
#   kafka:
#     bootstrap-servers: localhost:9092
#     template:
#       default-topic: account-creation
#     producer:
#       key-serializer: org.apache.kafka.common.serialization.StringSerializer
#       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs