server:
  port: 9090

spring: 
  application: 
    name: api-gateway

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Customer Service
      url: /aggregate/customer-service/v1/api-docs
    urls[1]:
      name: Account Service
      url: /aggregate/account-service/v1/api-docs
    urls[2]:
      name: Transaction Service
      url: /aggregate/transaction-service/v1/api-docs
  api-docs:
    path: /api-docs
    

api:
  services:
    customer:
      base-url: http://localhost:8081
    account:
      base-url: http://localhost:8082
    transaction:
      base-url: http://localhost:8083
    identity:
      base-url: http://localhost:8085
      relative-path: /api/identity/verify?username=

# Actuator Endpoints
management.health.circuitbreakers.enabled: true
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

#Resilinece4j Properties
resilience4j.circuitbreaker.configs.default.registerHealthIndicator: true
resilience4j.circuitbreaker.configs.default.slidingWindowType: COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize: 10
resilience4j.circuitbreaker.configs.default.failureRateThreshold: 50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState: 5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState: 3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled: true
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls: 5

#Resilience4J Timeout Properties
resilience4j.timelimiter.configs.default.timeout-duration: 3s

#Resilience4J Retry Properties
resilience4j.retry.configs.default.max-attempts: 3
resilience4j.retry.configs.default.wait-duration: 2s

# Actuator Endpoints
# management:
#   health:
#     circuitbreakers:
#       enabled: true
#   endpoints:
#     web:
#       exposure:
#         include: "*" 
#     health:
#       show-details: always

# #Resilinece4j Properties
# resilience4j:
#   circuitbreaker:
#     configs:
#       default:
#         registerHealthIndicator: true
#         slidingWindowType: COUNT_BASED
#         slidingWindowSize: 10
#         failureRateThreshold: 50
#         waitDurationInOpenState: 5s
#         permittedNumberOfCallsInHalfOpenState: 3
#         automaticTransitionFromOpenToHalfOpenEnabled: true
#         minimum-number-of-calls: 5
#   timelimiter:
#     configs:
#       default:
#         timeout-duration: 3s
#   retry:
#     configs:
#       default:
#         max-attempts: 3
#         wait-duration: 2s