server:
  port: 8081

spring: 
  application: 
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customer_service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
  console:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

api:
  services:
    account:
      base-url: http://localhost:8082
      relative-path: /api/account?customerId=
    transaction:
      base-url: http://localhost:8083
      relative-path: /api/transaction?customerId=