server:
  port: 8085

spring: 
  application: 
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: mydb@123
  jpa: 
    hibernate: 
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs