server: 
  port: 8083

spring:
  application: 
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_service
    username: root
    password: 123Oracle$
  jpa: 
    hibernate: 
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs